[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_todo = "CgigwV8UUzQiRHaMMgmXJ1u9bmq36xiASqjJRqKZgaWE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
